import scipy.io as sio
import random
#import numpy as np

#Simulate data generated by matlab toolbox GCCN which was developed by Anil Seth
matfile = u'C:\\Users\\Marijuana\\Desktop\\SimulationData.mat'#load .mat file
data = sio.loadmat(matfile)
X = data['X']
X_normal = X[:,:,0:50]#normal dataset
X_disturb = X[:,:,50:100]#disturbed dataset

for i in range(0,50):
    for j in range(0,5):
        temp = X_disturb[j,:,i]
        for times in range(0,400):#according to paper, we need generate 400 disturbed points
            Idx = random.randint(0,1999)#any index changing from 0 to 1999 might be disturbed
            X_disturb[j,Idx,i] = X_disturb[j,Idx,i]*(1+(int((random.randint(0,1)-0.5)*2))*random.uniform(1,2))
